import type { Property, Room, FloorUnit } from '@/types src'

export const PROPERTIES: Property[] = [
  {
    id: '1',
    slug: 'luxe-penthouse-bole',
    name: 'LUXE Penthouse',
    tagline: 'The Crown of Bole',
    type: 'Penthouse',
    status: 'available',
    tag: 'Flagship',
    location: 'Bole Medhanialem, Addis Ababa',
    city: 'Addis Ababa',
    price: 85000000,
    currency: 'ETB',
    priceLabel: 'ETB 85,000,000',
    beds: 5,
    baths: 6,
    area: 6200,
    floors: 12,
    description: 'The pinnacle of Addis Ababa luxury. A full-floor residence commanding the entire 12th level with 360° panoramic views across the city and beyond.',
    features: ['Private Elevator', 'Rooftop Terrace', 'Smart Home', 'Wine Cellar', 'Cinema Room', '24/7 Concierge'],
    images: ['/interiors/living.jpg', '/interiors/suite.jpg', '/interiors/terrace.jpg'],
    videoSrc: '/videos/interior.mp4',
    accentColor: '#C9B99A',
    coordinates: { lat: 8.9806, lng: 38.7578 },
  },
  {
    id: '2',
    slug: 'obsidian-sky-villa',
    name: 'Obsidian Sky Villa',
    tagline: 'Dark Luxury Defined',
    type: 'Sky Villa',
    status: 'available',
    tag: 'New Launch',
    location: 'Bole Medhanialem, Addis Ababa',
    city: 'Addis Ababa',
    price: 55000000,
    currency: 'ETB',
    priceLabel: 'ETB 55,000,000',
    beds: 4,
    baths: 4,
    area: 4850,
    description: 'Four-bedroom sky villa with floor-to-ceiling glazing and a private wraparound terrace suspended above the Addis Ababa skyline.',
    features: ['Sky Terrace', 'Jacuzzi', 'Smart Home', 'Private Gym', 'Concierge', 'Valet Parking'],
    images: ['/interiors/kitchen.jpg', '/interiors/living.jpg', '/interiors/suite.jpg'],
    videoSrc: '/interiors/tower.jpg',
    accentColor: '#4A7FA5',
    coordinates: { lat: 8.9806, lng: 38.7578 },
  },
  {
    id: '3',
    slug: 'sky-suite-501',
    name: 'Sky Suite 501',
    tagline: 'Above the Ordinary',
    type: 'Residence',
    status: 'reserved',
    tag: 'Limited',
    location: 'Bole Medhanialem, Addis Ababa',
    city: 'Addis Ababa',
    price: 32000000,
    currency: 'ETB',
    priceLabel: 'ETB 32,000,000',
    beds: 3,
    baths: 3,
    area: 3200,
    description: 'A curated three-bedroom residence with bespoke Italian furniture package and panoramic north-facing views of the Entoto hills.',
    features: ['City Views', 'Italian Furniture Package', 'Gym Access', 'Concierge', 'Secure Parking'],
    images: ['/interiors/suite.jpg', '/interiors/living.jpg', '/interiors/terrace.jpg'],
    accentColor: '#C9B99A',
    coordinates: { lat: 8.9806, lng: 38.7578 },
  },
]

export const ROOMS: Room[] = [
  {
    id: 'living',
    name: 'The Grand Living',
    type: 'Living Room',
    description: 'Vast open spaces defined by imported travertine floors, floor-to-ceiling glazing overlooking the Addis Ababa skyline, and bespoke furniture crafted by Italian artisans.',
    materials: ['Calacatta Marble', 'Brushed Bronze', 'Hand-stitched Leather'],
    area: '2,400 sqft',
    ceiling: '4.2m',
    image: '/interiors/living.jpg',
    accentColor: '#C9B99A',
  },
  {
    id: 'kitchen',
    name: 'The Obsidian Kitchen',
    type: 'Kitchen',
    description: 'Matte nero marquina cabinetry, Calacatta marble islands, and fully integrated Gaggenau appliances in a space designed for the culinary connoisseur.',
    materials: ['Nero Marquina', 'Gaggenau Appliances', 'Smoked Oak'],
    area: '980 sqft',
    ceiling: '3.8m',
    image: '/interiors/kitchen.jpg',
    accentColor: '#4A7FA5',
  },
  {
    id: 'suite',
    name: 'The Sky Suite',
    type: 'Master Bedroom',
    description: 'Hand-stitched silk headboards, climate-controlled wardrobes, and a panoramic dawn view that redefines waking up above the clouds.',
    materials: ['Raw Silk', 'Onyx Stone', 'Aged Walnut'],
    area: '1,800 sqft',
    ceiling: '3.6m',
    image: '/interiors/suite.jpg',
    accentColor: '#C9B99A',
  },
  {
    id: 'spa',
    name: 'The Wellness Sanctuary',
    type: 'Spa & Wellness',
    description: 'Hammam-inspired spa with infinity pool, cold plunge, steam room, and a meditation garden suspended above the city.',
    materials: ['Thassos Marble', 'Teak Wood', 'Volcanic Stone'],
    area: '1,200 sqft',
    ceiling: '3.4m',
    image: '/interiors/spa.jpg',
    accentColor: '#4A7FA5',
  },
  {
    id: 'terrace',
    name: 'The Sky Terrace',
    type: 'Private Terrace',
    description: 'An outdoor living room in the sky. Infinity-edge plunge pool, outdoor kitchen, and 360° panoramic views of the Addis Ababa horizon at golden hour.',
    materials: ['Teak Decking', 'Brushed Steel', 'Volcanic Stone'],
    area: '800 sqft',
    ceiling: 'Open Sky',
    image: '/interiors/terrace.jpg',
    accentColor: '#C9B99A',
  },
]

export const AMENITIES_DATA = [
  {
    id: 'spa',
    category: 'Wellness',
    name: 'The Obsidian Spa',
    tagline: 'Total Sensory Reset',
    description: 'A 3,200 sqft hammam-inspired sanctuary with private treatment rooms, cold plunge, steam cave, and a zero-gravity flotation pool.',
    features: ['Private Treatment Rooms', 'Hammam', 'Cold Plunge', 'Steam Cave', 'Flotation Pool'],
    level: 'Floors 1–2',
    image: '/interiors/spa.jpg',
    accentColor: '#4A7FA5',
    icon: '◈',
  },
  {
    id: 'gym',
    category: 'Fitness',
    name: 'Performance Studio',
    tagline: 'Elite Athletic Training',
    description: 'Technogym-equipped performance studio with personal training suites, altitude simulation chamber, and panoramic city-view yoga terrace.',
    features: ['Technogym Equipment', 'Personal Training', 'Altitude Chamber', 'Yoga Terrace', 'Recovery Suite'],
    level: 'Floor 3',
    image: '/interiors/gym.jpg',
    accentColor: '#C9B99A',
    icon: '⟐',
  },
  {
    id: 'restaurant',
    category: 'Fine Dining',
    name: 'Obsidian Sky Restaurant',
    tagline: 'Culinary Excellence Above the Clouds',
    description: 'A resident-priority fine dining experience helmed by an internationally trained chef, offering modern Ethiopian and Mediterranean cuisine with panoramic city views.',
    features: ['Fine Dining', 'Private Room', 'Bar & Lounge', 'Room Service', "Chef's Table"],
    level: 'Floor 11',
    image: '/interiors/restaurant.jpg',
    accentColor: '#C9B99A',
    icon: '◎',
  },
  {
    id: 'lounge',
    category: 'Social',
    name: 'Sky Lounge',
    tagline: 'Above the Ordinary',
    description: 'A resident-exclusive rooftop social space with curated bar, private dining pods, fire features, and 360° panoramic views of Addis Ababa.',
    features: ['Private Bar', 'Dining Pods', 'Fire Features', '360° Views', 'Event Space'],
    level: 'Rooftop',
    image: '/interiors/terrace.jpg',
    accentColor: '#C9B99A',
    icon: '◉',
  },
  {
    id: 'cinema',
    category: 'Entertainment',
    name: 'Private Cinema',
    tagline: 'First-Class Screening',
    description: '40-seat Dolby Atmos private cinema with cashmere recliners, premium sound isolation, and curated film library. Available for private hire.',
    features: ['Dolby Atmos', '40 Seats', 'Cashmere Recliners', 'Private Hire', 'Film Library'],
    level: 'Floor 2',
    image: '/interiors/cinema.jpg',
    accentColor: '#4A7FA5',
    icon: '▷',
  },
  {
    id: 'market',
    category: 'Lifestyle',
    name: 'LUXE Market Hall',
    tagline: 'Curated Daily Living',
    description: 'A curated artisan market featuring premium groceries, Ethiopian specialty foods, imported wines, fresh florals, and luxury essentials — all steps from your residence.',
    features: ['Artisan Groceries', 'Ethiopian Specialties', 'Imported Wines', 'Fresh Florals', 'Luxury Essentials'],
    level: 'Ground Floor',
    image: '/interiors/market.jpg',
    accentColor: '#C9B99A',
    icon: '⬡',
  },
  {
    id: 'parking',
    category: 'Security',
    name: 'Private Parking',
    tagline: 'Secure. Discreet. Exclusive.',
    description: 'Three levels of secure underground parking with dedicated resident bays, EV charging stations, valet service, and 24/7 CCTV monitoring.',
    features: ['Dedicated Bays', 'EV Charging', 'Valet Service', '24/7 CCTV', 'Guest Parking'],
    level: 'Basement B1–B3',
    image: '/interiors/parking.jpg',
    accentColor: '#4A7FA5',
    icon: '⊕',
  },
]

export const FLOOR_UNITS: Record<number, FloorUnit[]> = {
  12: [
    { id: '1201', floor: 12, type: 'Sky Penthouse', beds: 5, baths: 6, area: 6200, balconies: 4, status: 'available', price: 85000000 },
    { id: '1202', floor: 12, type: 'Penthouse', beds: 4, baths: 5, area: 4800, balconies: 3, status: 'reserved', price: 65000000 },
  ],
  11: [
    { id: '1101', floor: 11, type: 'Sky Villa', beds: 4, baths: 4, area: 4200, balconies: 2, status: 'available', price: 55000000 },
    { id: '1102', floor: 11, type: 'Sky Villa', beds: 3, baths: 3, area: 3400, balconies: 2, status: 'sold', price: 45000000 },
  ],
  10: [
    { id: '1001', floor: 10, type: '4 Bedroom', beds: 4, baths: 3, area: 3800, balconies: 2, status: 'available', price: 42000000 },
    { id: '1002', floor: 10, type: '3 Bedroom', beds: 3, baths: 3, area: 3000, balconies: 1, status: 'sold', price: 35000000 },
    { id: '1003', floor: 10, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'available', price: 28000000 },
  ],
  9: [
    { id: '901', floor: 9, type: '4 Bedroom', beds: 4, baths: 3, area: 3800, balconies: 2, status: 'sold', price: 40000000 },
    { id: '902', floor: 9, type: '3 Bedroom', beds: 3, baths: 3, area: 3000, balconies: 1, status: 'available', price: 33000000 },
    { id: '903', floor: 9, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'reserved', price: 26000000 },
  ],
  8: [
    { id: '801', floor: 8, type: '4 Bedroom', beds: 4, baths: 3, area: 3800, balconies: 2, status: 'available', price: 38000000 },
    { id: '802', floor: 8, type: '3 Bedroom', beds: 3, baths: 3, area: 3000, balconies: 1, status: 'available', price: 31000000 },
    { id: '803', floor: 8, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'sold', price: 24000000 },
    { id: '804', floor: 8, type: '1 Bedroom', beds: 1, baths: 1, area: 1400, balconies: 1, status: 'available', price: 16000000 },
  ],
  7: [
    { id: '701', floor: 7, type: '4 Bedroom', beds: 4, baths: 3, area: 3800, balconies: 2, status: 'reserved', price: 36000000 },
    { id: '702', floor: 7, type: '3 Bedroom', beds: 3, baths: 3, area: 3000, balconies: 1, status: 'available', price: 29000000 },
    { id: '703', floor: 7, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'available', price: 22000000 },
    { id: '704', floor: 7, type: '1 Bedroom', beds: 1, baths: 1, area: 1400, balconies: 1, status: 'sold', price: 15000000 },
  ],
  6: [
    { id: '601', floor: 6, type: '4 Bedroom', beds: 4, baths: 3, area: 3800, balconies: 2, status: 'available', price: 34000000 },
    { id: '602', floor: 6, type: '3 Bedroom', beds: 3, baths: 3, area: 3000, balconies: 1, status: 'sold', price: 27000000 },
    { id: '603', floor: 6, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'available', price: 21000000 },
    { id: '604', floor: 6, type: '1 Bedroom', beds: 1, baths: 1, area: 1400, balconies: 1, status: 'available', price: 14000000 },
  ],
  5: [
    { id: '501', floor: 5, type: 'Penthouse', beds: 3, baths: 3, area: 3200, balconies: 2, status: 'available', price: 45000000 },
    { id: '502', floor: 5, type: '4 Bed Penthouse', beds: 4, baths: 4, area: 4850, balconies: 3, status: 'available', price: 58000000 },
    { id: '503', floor: 5, type: '3 Bedroom', beds: 3, baths: 3, area: 2800, balconies: 1, status: 'reserved', price: 32000000 },
    { id: '504', floor: 5, type: '2 Bedroom', beds: 2, baths: 2, area: 1900, balconies: 1, status: 'sold', price: 22000000 },
  ],
  4: [
    { id: '401', floor: 4, type: '3 Bedroom', beds: 3, baths: 3, area: 3000, balconies: 1, status: 'sold', price: 25000000 },
    { id: '402', floor: 4, type: '3 Bedroom', beds: 3, baths: 3, area: 3000, balconies: 1, status: 'sold', price: 25000000 },
    { id: '403', floor: 4, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'available', price: 19000000 },
    { id: '404', floor: 4, type: '1 Bedroom', beds: 1, baths: 1, area: 1400, balconies: 1, status: 'available', price: 13000000 },
  ],
  3: [
    { id: '301', floor: 3, type: '3 Bedroom', beds: 3, baths: 3, area: 3000, balconies: 1, status: 'sold', price: 23000000 },
    { id: '302', floor: 3, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'sold', price: 18000000 },
    { id: '303', floor: 3, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'available', price: 18000000 },
    { id: '304', floor: 3, type: '1 Bedroom', beds: 1, baths: 1, area: 1400, balconies: 1, status: 'available', price: 12000000 },
  ],
  2: [
    { id: '201', floor: 2, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'sold', price: 17000000 },
    { id: '202', floor: 2, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'sold', price: 17000000 },
    { id: '203', floor: 2, type: '1 Bedroom', beds: 1, baths: 1, area: 1400, balconies: 1, status: 'available', price: 11000000 },
    { id: '204', floor: 2, type: '1 Bedroom', beds: 1, baths: 1, area: 1400, balconies: 1, status: 'available', price: 11000000 },
  ],
  1: [
    { id: '101', floor: 1, type: '2 Bedroom', beds: 2, baths: 2, area: 2200, balconies: 1, status: 'available', price: 15000000 },
    { id: '102', floor: 1, type: '1 Bedroom', beds: 1, baths: 1, area: 1400, balconies: 1, status: 'available', price: 10000000 },
  ],
  0: [],
}

export const TESTIMONIALS = [
  {
    id: '1',
    quote: 'LUXE did not sell us a property. They handed us a new way of living. Every detail — from the marble sourcing to the smart home calibration — was executed with obsessive precision.',
    author: 'Khalid Al Mansouri',
    title: 'CEO, Al Mansouri Holdings',
    location: 'Dubai, UAE',
    initial: 'K',
  },
  {
    id: '2',
    quote: 'In thirty years of acquiring prime real estate across three continents, I have never encountered a team that combines architectural vision with genuine personal care the way LUXE does.',
    author: 'Soliyana Bekalu',
    title: 'Private Equity Partner',
    location: 'Addis Ababa, Ethiopia',
    initial: 'S',
  },
  {
    id: '3',
    quote: 'As Ethiopia\'s real estate market matures, LUXE stands alone at the pinnacle. Their development is a landmark that will define the city\'s skyline for generations to come.',
    author: 'Dawit Bekele',
    title: 'Managing Director, Bekele Group',
    location: 'Addis Ababa, Ethiopia',
    initial: 'D',
  },
  {
    id: '4',
    quote: 'The Sky Terrace alone is worth the investment. Watching the sun rise over Entoto from your private pool — there is nothing else like it in this city.',
    author: 'Meron Haile',
    title: 'Founder, Haile Hospitality',
    location: 'Addis Ababa, Ethiopia',
    initial: 'M',
  },
]